/**********************************************************/
/* Automatically generated by './mkconfig': do note edit! */
/**********************************************************/
#define LGL_OS "Darwin eduroam-202.fi.muni.cz 12.5.0 x86_64"
#define LGL_COMPILED "Tue Oct  8 13:26:22 CEST 2013"
#define LGL_RELEASED "Mon Apr 29 23:59:16 CEST 2013"
#define LGL_VERSION "aqw"
#define LGL_ID "27d9fd46b7165001d2b9810598c94c5acf3cda9d"
